disable testing and pushing to quay.io for CentOS7 image + enable tfaga wrapper
sclorg/s2i-base-container pull request #272
Opened 2023-07-20 08:52 UTC by zmiklank

2023-07-20 08:52 UTC, zmiklank commented
[test]

2023-07-24 11:11 UTC, phracek commented on .github/workflows/build-and-push.yml
> +
Why empty lines?

2023-07-24 11:12 UTC, phracek requested changes
This pull request combines two big changes. I would split into two pull request. One for tfaga wrapper and second of for CentOS 7 image.

2023-07-24 14:07 UTC, zmiklank commented on .github/workflows/build-and-push.yml
> +
I inserted new lines because I wanted to increase a readability of the file.
Without the empty lines is really difficult to go through git diff when some value of some lines are changed.

2023-07-24 14:08 UTC, zmiklank commented
> This pull request combines two big changes. I would split into two pull request. One for tfaga wrapper and second of for CentOS 7 image.

Sure.

2023-07-24 14:11 UTC, zmiklank commented
I have just removed the last commit -- will create separate PR when this one is merged.

2023-07-25 08:47 UTC, phracek commented
[test]

2023-07-25 12:20 UTC, merged