use correct path to Dockerfiles for container CI
sclorg/s2i-base-container pull request #275
Opened 2023-08-01 12:07 UTC by zmiklank

uses changes from this PS: https://github.com/sclorg/tfaga-wrapper/pull/11

2023-08-01 12:35 UTC, jamacku commented on .github/workflows/container-tests.yml
> +          working_dir: ${{ matrix.working_dir }}
```suggestion
          working_dir: ${{ matrix.version }}
```

2023-08-01 12:37 UTC, zmiklank commented on .github/workflows/container-tests.yml
> +          working_dir: ${{ matrix.working_dir }}
Thanks for catching this.

2023-08-01 13:01 UTC, phracek requested changes
Please have a look at my comments.

2023-08-01 13:02 UTC, phracek requested changes

2023-08-01 13:02 UTC, phracek commented on .github/workflows/container-tests.yml
> +          working_dir: ${{ matrix.version }}
One more thing. Please be aware, the first to be tested `core` container, and later on `base` container.

2023-08-01 14:17 UTC, zmiklank commented on .github/workflows/container-tests.yml
> +          working_dir: ${{ matrix.version }}
> One more thing. Please be aware, the first to be tested core container, and later on base container.

Could you please explain to me what benefit would it bring?

2023-08-01 14:33 UTC, phracek commented on .github/workflows/container-tests.yml
> +          working_dir: ${{ matrix.version }}
Sorry not tested but build. Let's say, that someone does a fix in `core` container. The change should be visible after building also in `base` container. In the case of `RPM` world, if we add a package to `core` container, then in the wrong order of build `base` container will not contain this specific RPM.

2023-08-01 14:46 UTC, zmiklank commented on .github/workflows/container-tests.yml
> +          working_dir: ${{ matrix.version }}
I think this can not be adjusted in the GitHub Action itself. If `core` version is passed, then `core` image is built, if `base` version, then `base` image, and if version is empty, then both images are built subsequently.

If we just run `core` build and then in other job the `base` build, then the `base` will pull the `core` from quay.io anyway, imo.

2023-08-02 07:51 UTC, phracek approved these changes

2023-08-03 11:27 UTC, merged