Switch using NodeJS from version 14 to version 20
sclorg/s2i-base-container pull request #285
Opened 2023-11-16 15:04 UTC by phracek

Switch using NodeJS from version 14 to version 20

NodeJS version 14 reached EOL and version 20
was already introduced.

Also Dockerfile's checks if npm -v corresponds with RHEL8 and RHEL9 version

2023-11-16 15:05 UTC, phracek commented
[test]

2023-11-20 08:11 UTC, zmiklank requested changes
Hi.
This solution does not work for RHEL9, as it does not use nodejs from module (yet).
Thanks for you work!.

2023-11-20 09:27 UTC, phracek commented
[test]

2023-11-20 10:57 UTC, hhorak commented
> This solution does not work for RHEL9, as it does not use nodejs from module (yet).

nodejs:20 is a module in RHEL-9 actually, so it should work the same as in RHEL-8.

2023-11-20 10:59 UTC, zmiklank commented
> > This solution does not work for RHEL9, as it does not use nodejs from module (yet).
> 
> nodejs:20 is a module in RHEL-9 actually, so it should work the same as in RHEL-8.

@hhorak Right, but when I commented on this PR the module was not enabled in the Dockerfile yet. Peto already fixed it.

2023-11-20 11:03 UTC, zmiklank commented
LGTM for RHELs. What about other distros? Do we want to keep there the nodejs version which has been there already?

2023-11-20 13:20 UTC, zmiklank commented
[test]

2023-11-20 13:20 UTC, zmiklank approved these changes
LGTM. Thanks. Feel free to merge when tests are green :).

2023-11-20 13:38 UTC, merged