add support for f40
sclorg/s2i-base-container pull request #289
Opened 2024-02-14 12:26 UTC by zmiklank

Start building and pushing to quay.io s2i-base and s2i-core images for f40.
We planned to support 2 Fedora version simultaneously, but this decision has been revised.
Only tested version is still f38.

2024-02-15 07:43 UTC, phracek requested changes
Please address my comments

2024-02-15 07:43 UTC, phracek commented on core/Dockerfile.f40
> +    VERSION=38 \
Typo here.

2024-02-15 09:12 UTC, zmiklank commented on core/Dockerfile.f40
> +    VERSION=38 \
Good catch. The same problem is with f39. Will fix that.

2024-02-16 10:06 UTC, phracek approved these changes

2024-02-16 10:06 UTC, merged